### ISSUE TITLE
Prepare Jakarta Servlet for Jakarta EE 8 Release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/servlet-api#243]
### Tasks

- [x] Update text files
- [x] Generate "boilerplate" specification project
- [x] Make a staging release
- [x] Generate Stand-alone TCK test results
- [x] Submit a PR to jakartaee/specifications repository
- [x] Update the Jakarta EE API jar by submitting a PR to the [jakartaee-api](https://github.com/eclipse-ee4j/jakartaee-api) project

See [here](https://wiki.eclipse.org/How_to_Prepare_API_Projects_to_Jakarta_EE_8_Release) for detailed instructions.

**Comment by arjantijms** [comment]
[API PR](https://github.com/eclipse-ee4j/jakartaee-api/pull/19)

**Comment by arjantijms** [comment]
[Github pages requested](https://bugs.eclipse.org/bugs/show_bug.cgi?id=549725)
