### ISSUE TITLE
Deliver servlet-api Specification Version update for Jakarta EE 9

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/servlet-api#286]
**Is your feature request related to a problem? Please describe.**
Jakarta EE 9 is the next major release, with the main focus of moving from the ```javax``` namespace to the ```jakarta``` namespace.

**Describe the solution you'd like**
This issue will be used to track the progress of this work effort via the [Jakarta EE 9 Project board](https://github.com/orgs/eclipse-ee4j/projects/17).

**Additional context**
[Jakarta EE Specification Process](https://jakarta.ee/about/jesp/)
[Eclipse Project Handbook](https://www.eclipse.org/projects/handbook/#release)
[Eclipse Release Record for Jakarta EE 9](https://projects.eclipse.org/projects/ee4j.jakartaee-platform/releases/9)

**ToDo**
- [x] **[Create Eclipse Release Record](https://www.eclipse.org/projects/handbook/#pmi-commands-release) in your respective Jakarta Specification Project.**
 Most Component Release Records will just reference the [Jakarta EE 9 Platform Release Plan](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan).  But, if your Component deviates at all from the Platform Release Plan, then a description of the changes will be required in the Release Record.
https://projects.eclipse.org/projects/ee4j.servlet/releases/5.0
- [x] **Initiate a ballot for your Jakarta Release Record/Plan.** - N/A
 Again, if your component is only doing the required minimum as defined by the [Jakarta EE 9 Platform Release Plan](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan), then no separate ballot is required.  You are already approved.  But, if your component deviates from the Platform Release Plan, then you will need to initiate your own ballot as defined by the [Jakarta EE Specification Process](https://jakarta.ee/about/jesp/).
- [x] **Jakarta-ize your Specification document (if applicable)**
 Many of the Jakarta EE components now have the source for their Specification documents.  It is strongly recommended that these Specification documents are properly updated to represent Jakarta EE instead of Java EE.  Some [helpful instructions are documented](https://github.com/jakartaee/specification-committee/blob/master/steps_javaee_to_jakartaee.adoc) here.
- [x] **javax -> jakarta Spec updates**
 If your component has Specification source, then all javax package references need to be updated to use jakarta package references.
- [x] **javax -> jakarta API updates**
 Your component APIs need to move from using the javax namespace to using the jakarta namespace.
- [x] **Release Candidate (RC) of Jakarta API in Maven Central**
 A Release Candidate of your component API should be pushed to Maven Central as soon as humanly possible.  This will allow other dependent components to utilize your APIs as they are updating their APIs.  Multiple revisions of these Release Candidate APIs are allowed (and probably expected) during the development cycle.
- [x] **javax -> jakarta TCK updates**
 Your component TCK needs to be updated to use the jakarta namespace.
- [x] **javax -> jakarta Compatible Implementation updates**
 Your compatible implementation that will be used to demonstrate completeness of the Specification needs to be updated to use the jakarta namespace.
- [x] **Final Jakarta API available in Staging Repo**
 When ready, your final version of the API needs to be staged to get ready for the PR review and approvals.
- [x] **Draft Specification and Apidoc PRs ready for review**
 Like we did for Jakarta EE 8, draft PRs need to be created and reviewed in preparation for the final ballots.
- [x] **Release Review Ballot started**
 Each Jakarta EE component will need to initiate a separate Release Review ballot after proper reviewing has completed.  To be clear, there will not be a blanket Release Review for all of Jakarta EE 9 like we did for the Plan Review.  Each component needs a separate Release Review.

**Comment by kwsutter** [comment]
Can I ask this team to please create and assign the following labels to this Issue?  Thank you!
[Epic]
[wave:1]

I noticed that the [Epic] label has been assigned and removed...  In order to help us track the progress of the overall Jakarta EE 9 release, we've asked for the Spec Projects to help out with some Issue labeling (for those Projects where I do not have committer access).  Thanks for your help!

**Comment by pnicolucci** [comment]
@kwsutter, added a link to the Maven artifacts : https://github.com/orgs/eclipse-ee4j/projects/17#card-31971280

**Comment by pnicolucci** [comment]
Removing check from `Release Candidate (RC) of Jakarta API in Maven Central` as I don't an RC out on Maven Central, I only see an M1.

**Comment by kwsutter** [comment]
Now that we have adjusted the requirement for a Milestone vs RC API jar file, could we get the Servlet 5.0 M1 API mentioned via a Notecard in the [Milestone/RC column of the Project Board](https://github.com/orgs/eclipse-ee4j/projects/17#column-7346435)?  Thanks!

**Comment by kwsutter** [comment]
I went ahead and created the Servlet 5.0 Release Record:  https://projects.eclipse.org/projects/ee4j.servlet/releases/5.0

I have also updated the checklist to show that this was completed.  I also marked the Release 
Plan Review work item since this was covered by the overall Jakarta EE 9 Release Plan review.

**Comment by thadumi** [comment]
Hi, if there is nobody taking care of the specification, I'd like to update it.

**Comment by stuartwdouglas** [comment]
Do you mean the spec document? If so I don't think anyone is working on it currently. I went through and fixed all the formatting a while ago, but did not update the text.

**Comment by arjantijms** [comment]
Compatible implementation updated in 

* Grizzly: https://github.com/eclipse-ee4j/grizzly/commit/dd47074c3f87fdce0351685c49c6327112cd5ba7 staged at: https://jakarta.oss.sonatype.org/content/repositories/staging/org/glassfish/grizzly/grizzly-core/3.0.0-M1/
* GlassFish: https://github.com/eclipse-ee4j/glassfish/commit/1eecede1dc7fe83ffe7bdd034c7a95b38b9fa2b6 and others

**Comment by arjantijms** [comment]
TCK updated in https://github.com/eclipse-ee4j/jakartaee-tck/commit/67aca21b09373182d4caf0af6e271f9e58e1430e#diff-45054851fcf26fdebe793539a039d8f4

**Comment by kwsutter** [comment]
One last request for the Specifications PR to promote the Milestone deliverables for this Project.  The PR is created against the [Jakarta EE specifications github repo](https://github.com/jakartaee/specifications/pulls).  A template is automatically used when creating PRs against this repo which should help with understanding the steps required for a successful merge.  We're not looking for perfection for this Milestone.  We just want the ability to promote the great work that all of the Projects are doing.

If you submit a PR, please feel free to move this Epic to the [Milestone 1 Ready column in the Project Board](https://github.com/orgs/eclipse-ee4j/projects/17#column-9442495).  Thanks!

**Comment by kwsutter** [comment]
Looking for an update on the status of the Servlet Final Specification PR.  If we're going to make the [Sept deliverable goal](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9#jakarta-ee-9-schedule), then this Wave 1 Specification needs to be ready for final ballot by Monday, July 19.  Which means that the Specification PRs should already be created and under a "mentorship" review.  Can I ask what the plans are for this Specification?  Thanks!

**Comment by markt-asf** [comment]
I believe the API work is complete. There are some clarifications it would be good but not essential to include.
The specification document is still in progress. I'm currently about 50% of the way through a side-by-side comparison with the 4.0 spec doc to check the conversion process hasn't garbled the formatting, section numbering, cross-references etc.
The current issues have not yet been reviewed and there are various aspects of the POM that need to be double checked.
This is currently what I am working on.

**Comment by arjantijms** [comment]
> Final Jakarta API available in Staging Repo

https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/servlet/jakarta.servlet-api/5.0.0/

**Comment by arjantijms** [comment]
> Draft Specification and Apidoc PRs ready for review

https://github.com/jakartaee/specifications/pull/232

**Comment by arjantijms** [comment]
Ballot: https://www.eclipse.org/lists/jakarta.ee-spec/msg00898.html

**Comment by arjantijms** [comment]
Completion steps: https://github.com/eclipse-ee4j/servlet-api/issues/366

**Comment by arjantijms** [comment]
- [X] Conclusion of review: https://bugs.eclipse.org/bugs/show_bug.cgi?id=566965#c6
